// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Operator handling.
//!
//! ## Phase 4d — same architectural blocker as sqlink
//! (2026-06-24)
//!
//! DuckDB's parser tokenises operators at compile time too.
//! Custom symbols like `&&&` or `<#>` are unrecognised tokens
//! — `SELECT g1 &&& g2` is a parse error before any function
//! dispatch could intervene. DuckDB DOES recognise some
//! symbols (`<<`, `>>`, etc.) and could in principle bind them
//! to scalar functions, but the registration API isn't exposed
//! from duckdb-rs (same Connection-internals problem).
//!
//! ## Where this work actually lives
//!
//! SQL-preprocessing concern, not extension concern. The
//! proper home is a separate `ducklink-preprocess` crate that:
//!
//!   - Parses SQL via sqlparser-rs (DuckDB dialect)
//!   - Rewrites operators: `g1 && g2` → `st_bboxintersects(g1, g2)`
//!   - Rewrites casts to user-types: same approach
//!   - Hands rewritten SQL to duckdb-rs's `prepare`/`execute`
//!
//! That crate can be generated from the same BridgePlan but
//! is a separate target.

use duckdb::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Operators the shim advertises.
// ----------------------------------------------------------------------

// === extension: postgis ===
// `&&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersects
// `&&` (lhs=Some(2003), rhs=Some(2003))  →  st_bboxintersects
// `&&` (lhs=Some(2004), rhs=Some(2004))  →  st_bboxintersects
// `&&&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersectsnd
// `&/&` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxintersects2d
// `&<` (lhs=Some(2001), rhs=Some(2001))  →  st_overleft
// `&<` (lhs=Some(2004), rhs=Some(2004))  →  st_overleft
// `&<|` (lhs=Some(2001), rhs=Some(2001))  →  st_overbelow
// `&<|` (lhs=Some(2004), rhs=Some(2004))  →  st_overbelow
// `&>` (lhs=Some(2001), rhs=Some(2001))  →  st_overright
// `&>` (lhs=Some(2004), rhs=Some(2004))  →  st_overright
// `<` (lhs=Some(2001), rhs=Some(2001))  →  st_lt
// `<#>` (lhs=Some(2001), rhs=Some(2001))  →  st_bboxdistance
// `<->` (lhs=Some(2001), rhs=Some(2001))  →  st_knndistance
// `<->` (lhs=Some(2003), rhs=Some(2003))  →  st_knndistance
// `<<` (lhs=Some(2001), rhs=Some(2001))  →  st_left
// `<<` (lhs=Some(2004), rhs=Some(2004))  →  st_left
// `<<->>` (lhs=Some(2001), rhs=Some(2001))  →  st_distancecentroidnd
// `<<@` (lhs=Some(2001), rhs=Some(2001))  →  st_withinnd
// `<<|` (lhs=Some(2001), rhs=Some(2001))  →  st_below
// `<<|` (lhs=Some(2004), rhs=Some(2004))  →  st_below
// `<=` (lhs=Some(2001), rhs=Some(2001))  →  st_le
// `<>` (lhs=Some(2001), rhs=Some(2001))  →  st_neq
// `=` (lhs=Some(2001), rhs=Some(2001))  →  st_eq
// `=` (lhs=Some(2003), rhs=Some(2003))  →  st_eq
// `=` (lhs=Some(2004), rhs=Some(2004))  →  raster_eq
// `>` (lhs=Some(2001), rhs=Some(2001))  →  st_gt
// `>=` (lhs=Some(2001), rhs=Some(2001))  →  st_ge
// `>>` (lhs=Some(2001), rhs=Some(2001))  →  st_right
// `>>` (lhs=Some(2004), rhs=Some(2004))  →  st_right
// `@` (lhs=Some(2001), rhs=Some(2001))  →  st_within
// `@>>` (lhs=Some(2001), rhs=Some(2001))  →  st_containsnd
// `@@` (lhs=Some(2001), rhs=Some(2001))  →  st_withinnd
// `|&>` (lhs=Some(2001), rhs=Some(2001))  →  st_overabove
// `|&>` (lhs=Some(2004), rhs=Some(2004))  →  st_overabove
// `|=|` (lhs=Some(2001), rhs=Some(2001))  →  st_distancecpa
// `|>>` (lhs=Some(2001), rhs=Some(2001))  →  st_above
// `|>>` (lhs=Some(2004), rhs=Some(2004))  →  st_above
// `~` (lhs=Some(2001), rhs=Some(2001))  →  st_contains
// `~=` (lhs=Some(2001), rhs=Some(2001))  →  st_equals
// `~==` (lhs=Some(2001), rhs=Some(2001))  →  st_samend
// `~~` (lhs=Some(2001), rhs=Some(2001))  →  st_containsnd
// `~~=` (lhs=Some(2001), rhs=Some(2001))  →  st_samend
