// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Token-level preprocessor patterns.
//!
//! ## Phase 4d — see operators.rs for the architectural picture.

use duckdb::{Connection, Result};

pub fn register_all(_conn: &Connection) -> Result<()> {
    Ok(())
}

// ----------------------------------------------------------------------
// Preprocessor patterns the shim advertises.
// ----------------------------------------------------------------------

// === extension: postgis ===
// token `<#>` → st_bboxdistance
// token `<->` → st_knndistance
// token `<<->>` → st_distancecentroidnd
// token `|=|` → st_distancecpa
// token `~==` → st_samend
