// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Table-function (UDTF) registration via raw libduckdb-sys.
//!
//! ## Phase 5 (2026-06-25) — WIRED
//!
//! Each shim UDTF is registered through DuckDB's C
//! table-function API (`duckdb_create_table_function` + the
//! bind/init/function callbacks). DuckDB's `VTab` bind/init
//! hooks are *static* — they don't know which registered name
//! they're serving — so we dispatch dynamically by stashing the
//! resolved `Arc<dyn TableFunctionDef>` on the function's
//! ExtraInfo (mirrors how aggregates carry their def). One
//! generic dispatcher serves every UDTF regardless of arity or
//! signature, so a future shim's table functions wire up with
//! no per-shim code.
//!
//! ### One arity per name (DuckDB C-API limitation)
//!
//! Unlike the scalar C API (which has a function-set abstraction
//! for positional overloads), DuckDB's loadable table-function
//! C API binds by EXACT positional arity and keeps a single
//! catalog entry per name. We therefore register each name once,
//! with its NARROWEST recorded signature (the most broadly
//! callable form). Wider positional overloads — e.g.
//! `st_subdivide(geom, maxvertices)` on top of
//! `st_subdivide(geom)` — can't coexist under the same name and
//! are noted as comments in `register_all`. The chosen
//! signature's parameter types come from the interface DB.
//!
//! Lifecycle:
//!
//!   bind  — read each SQL parameter via `bind_get_parameter`
//!           (typed from `def.param_types()`), build the
//!           `FunctionValue` argument vector, derive the output
//!           column schema from `def.output_schema(input_types)`
//!           and declare it via `bind_add_result_column`. The
//!           args + the per-column output DataTypes are stored
//!           in the BindData.
//!
//!   init  — call `def.execute(&args)` to obtain a
//!           `Box<dyn TableFunctionIterator>`; park it (behind a
//!           Mutex, since DuckDB may call `function` from a
//!           worker thread) in the InitData. We force
//!           single-threaded scan (`init_set_max_threads(1)`)
//!           because the shim iterator is a stateful handle into
//!           the wasm Store and is not parallel-safe.
//!
//!   func  — pull `iter.next_row()` up to one vector's worth of
//!           rows, writing each column value to the matching
//!           output vector; set the produced chunk size. An
//!           empty chunk signals end-of-scan to DuckDB.

use std::ffi::{c_char, c_void, CString};
use std::sync::Arc;

use parking_lot::Mutex;

use libduckdb_sys::{
    self as ffi, duckdb_bind_add_result_column, duckdb_bind_get_extra_info,
    duckdb_bind_get_parameter, duckdb_bind_get_parameter_count, duckdb_bind_info,
    duckdb_bind_set_bind_data, duckdb_bind_set_error, duckdb_connection,
    duckdb_create_table_function, duckdb_data_chunk, duckdb_data_chunk_set_size,
    duckdb_destroy_table_function, duckdb_function_get_bind_data, duckdb_function_get_init_data,
    duckdb_function_info, duckdb_function_set_error, duckdb_init_get_bind_data, duckdb_init_info,
    duckdb_init_set_init_data, duckdb_init_set_max_threads, duckdb_register_table_function,
    duckdb_table_function_add_parameter, duckdb_table_function_set_bind,
    duckdb_table_function_set_extra_info, duckdb_table_function_set_function,
    duckdb_table_function_set_init, duckdb_table_function_set_name, idx_t, DuckDBSuccess,
};

use datafission_functions::traits::{ColumnInfo, TableFunctionDef, TableFunctionIterator};
use datafission_functions::types::FunctionValue;
use datafission_functions::DataType;

use crate::registry;

/// Per-registration state stashed on the table function via
/// `duckdb_table_function_set_extra_info`; recovered in `bind`.
///
/// `param_types` is the SPECIFIC overload signature this DuckDB
/// table-function registration serves. A UDTF with N distinct
/// argument-count overloads (e.g. `st_subdivide(blob)` and
/// `st_subdivide(blob, int32)`) is registered N times — once per
/// overload — each carrying its own `param_types` so `bind` reads
/// each positional argument with the right getter.
struct TfExtraInfo {
    def: Arc<dyn TableFunctionDef>,
    param_types: Vec<DataType>,
}

/// Produced by `bind`, consumed by `init` / `func`. Holds the
/// evaluated call arguments + the resolved def + the output
/// column DataTypes (so `func` knows how to write each column).
struct TfBindData {
    def: Arc<dyn TableFunctionDef>,
    args: Vec<FunctionValue>,
    out_types: Vec<DataType>,
}

/// Per-scan state produced by `init`. The shim iterator is a
/// stateful wasm handle, so it lives behind a Mutex and the scan
/// runs single-threaded.
///
/// `tag` is the leading field (and is always `INIT_OK_TAG`) so a
/// single-byte read at the box head can distinguish this from the
/// error sentinel `TfInitErr` — both arrive through the same
/// `duckdb_init_set_init_data` slot and `func` must tell them
/// apart. `#[repr(C)]` pins `tag` first.
#[repr(C)]
struct TfInitData {
    tag: u8,
    iter: Mutex<Box<dyn TableFunctionIterator>>,
    out_types: Vec<DataType>,
    done: bool,
}

/// Register every UDTF the shim publishes.
///
/// # Safety
///
/// `conn` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(conn: duckdb_connection) {
    register_table_function(conn, "st_dump", &[DataType::Binary]);
    register_table_function(conn, "st_dump_points", &[DataType::Binary]);
    register_table_function(conn, "st_dump_rings", &[DataType::Binary]);
    register_table_function(conn, "st_dump_segments", &[DataType::Binary]);
    register_table_function(conn, "st_dumppoints", &[DataType::Binary]);
    register_table_function(conn, "st_dumprings", &[DataType::Binary]);
    register_table_function(conn, "st_dumpsegments", &[DataType::Binary]);
    register_table_function(
        conn,
        "st_hexagon_grid",
        &[DataType::Float64, DataType::Binary],
    );
    register_table_function(
        conn,
        "st_hexagongrid",
        &[DataType::Float64, DataType::Binary],
    );
    register_table_function(
        conn,
        "st_square_grid",
        &[DataType::Float64, DataType::Binary],
    );
    register_table_function(
        conn,
        "st_squaregrid",
        &[DataType::Float64, DataType::Binary],
    );
    register_table_function(conn, "st_subdivide", &[DataType::Binary, DataType::Int64]);
    // Phase 5: 12 canonical UDTFs + 0 alias registrations (0 wider positional overloads not expressible via the C API).
}

unsafe fn register_table_function(
    conn: duckdb_connection,
    sql_name: &str,
    param_types: &[DataType],
) {
    let def = match registry::lookup_table(sql_name) {
        Some(d) => d,
        None => {
            eprintln!("[shim-table-functions] no shim entry for `{sql_name}` — skipping");
            return;
        }
    };
    let param_types: Vec<DataType> = param_types.to_vec();

    let tf = duckdb_create_table_function();
    let name_cs = match CString::new(sql_name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-table-functions] name contains NUL: `{sql_name}` — skipping");
            duckdb_destroy_table_function(&mut { tf });
            return;
        }
    };
    duckdb_table_function_set_name(tf, name_cs.as_ptr());

    // Declare positional parameters for this overload. DuckDB
    // needs them to bind `SELECT * FROM fn(a, b, ...)`. The bind
    // callback re-reads the live values; these declarations fix
    // arity + coarse type so the planner accepts the call.
    for dt in &param_types {
        let lt = ffi::duckdb_create_logical_type(logical_type_id_for(dt));
        duckdb_table_function_add_parameter(tf, lt);
        let mut to_destroy = lt;
        ffi::duckdb_destroy_logical_type(&mut to_destroy);
    }

    duckdb_table_function_set_bind(tf, Some(bind_callback));
    duckdb_table_function_set_init(tf, Some(init_callback));
    duckdb_table_function_set_function(tf, Some(func_callback));

    // Park the per-registration def + this overload's param types.
    // The Box is leaked here and reclaimed when DuckDB calls the
    // destructor.
    let extra = Box::into_raw(Box::new(TfExtraInfo {
        def: Arc::clone(&def),
        param_types,
    }));
    duckdb_table_function_set_extra_info(tf, extra as *mut c_void, Some(drop_extra_info));

    let rc = duckdb_register_table_function(conn, tf);
    duckdb_destroy_table_function(&mut { tf });
    if rc != DuckDBSuccess {
        eprintln!("[shim-table-functions] could not register `{sql_name}` (rc={rc})");
    }
}

/// Map a DataFission `DataType` to the DuckDB C `DUCKDB_TYPE_*`
/// id used for both parameter declarations and output columns.
fn logical_type_id_for(dt: &DataType) -> ffi::duckdb_type {
    match dt {
        DataType::Boolean => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BOOLEAN,
        DataType::Int8 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_TINYINT,
        DataType::Int16 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_SMALLINT,
        DataType::Int32 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_INTEGER,
        DataType::Int64 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BIGINT,
        DataType::UInt8 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_UTINYINT,
        DataType::UInt16 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_USMALLINT,
        DataType::UInt32 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_UINTEGER,
        DataType::UInt64 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_UBIGINT,
        DataType::Float32 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_FLOAT,
        DataType::Float64 => ffi::DUCKDB_TYPE_DUCKDB_TYPE_DOUBLE,
        DataType::Char { .. } | DataType::Varchar { .. } | DataType::Text => {
            ffi::DUCKDB_TYPE_DUCKDB_TYPE_VARCHAR
        }
        DataType::Binary => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB,
        // Anything we don't have an explicit mapping for falls
        // back to BLOB — the shim ABI is byte-oriented, so a BLOB
        // column round-trips arbitrary payloads losslessly.
        _ => ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB,
    }
}

// =====================================================================
// C callbacks. All `unsafe extern "C"` because DuckDB calls them.
// =====================================================================

unsafe extern "C" fn bind_callback(info: duckdb_bind_info) {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| bind_inner(info))) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => bind_set_err(info, &msg),
        Err(_) => bind_set_err(info, "panic in table-function bind"),
    }
}

unsafe fn bind_inner(info: duckdb_bind_info) -> std::result::Result<(), String> {
    let extra = &*(duckdb_bind_get_extra_info(info) as *const TfExtraInfo);
    let def = Arc::clone(&extra.def);

    // This registration's specific overload signature tells us how
    // to interpret each positional argument's value.
    let want = extra.param_types.clone();

    let n = duckdb_bind_get_parameter_count(info) as usize;
    let mut args: Vec<FunctionValue> = Vec::with_capacity(n);
    let mut input_types: Vec<DataType> = Vec::with_capacity(n);
    for i in 0..n {
        let dt = want.get(i).cloned().unwrap_or(DataType::Binary);
        let val = duckdb_bind_get_parameter(info, i as idx_t);
        if val.is_null() {
            return Err(format!(
                "table function `{}`: parameter {i} is null",
                def.name()
            ));
        }
        let fv = read_value(val, &dt);
        let mut v = val;
        ffi::duckdb_destroy_value(&mut v);
        args.push(fv);
        input_types.push(dt);
    }

    // Derive + declare the output schema. An empty schema means
    // the shim couldn't express the output columns (e.g. an
    // input type not representable in the WIT logical-type set) —
    // surface that as a bind error rather than a 0-column table.
    let schema: Vec<ColumnInfo> = def.output_schema(&input_types);
    if schema.is_empty() {
        return Err(format!(
            "table function `{}`: shim returned an empty output schema",
            def.name()
        ));
    }
    let mut out_types: Vec<DataType> = Vec::with_capacity(schema.len());
    for col in &schema {
        let c_name = CString::new(col.name.as_str())
            .map_err(|_| format!("output column name contains NUL: {}", col.name))?;
        let lt = ffi::duckdb_create_logical_type(logical_type_id_for(&col.data_type));
        duckdb_bind_add_result_column(info, c_name.as_ptr(), lt);
        let mut to_destroy = lt;
        ffi::duckdb_destroy_logical_type(&mut to_destroy);
        out_types.push(col.data_type.clone());
    }

    let bind = Box::into_raw(Box::new(TfBindData {
        def,
        args,
        out_types,
    }));
    duckdb_bind_set_bind_data(info, bind as *mut c_void, Some(drop_bind_data));
    Ok(())
}

unsafe extern "C" fn init_callback(info: duckdb_init_info) {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| init_inner(info))) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => {
            // init has no set_error of its own; surface via a
            // poisoned init-data carrying the message, picked up by
            // the first func call.
            let init = Box::into_raw(Box::new(TfInitErr {
                tag: INIT_ERR_TAG,
                msg,
            }));
            duckdb_init_set_init_data(info, init as *mut c_void, Some(drop_init_err));
        }
        Err(_) => {
            let init = Box::into_raw(Box::new(TfInitErr {
                tag: INIT_ERR_TAG,
                msg: "panic in table-function init".into(),
            }));
            duckdb_init_set_init_data(info, init as *mut c_void, Some(drop_init_err));
        }
    }
}

unsafe fn init_inner(info: duckdb_init_info) -> std::result::Result<(), String> {
    let bind = &*(duckdb_init_get_bind_data(info) as *const TfBindData);
    let iter = bind.def.execute(&bind.args).map_err(|e| format!("{e:?}"))?;
    // The shim iterator is a single stateful wasm handle; force a
    // single-threaded scan so DuckDB doesn't call `func`
    // concurrently across worker threads.
    duckdb_init_set_max_threads(info, 1);
    let init = Box::into_raw(Box::new(TfInitData {
        tag: INIT_OK_TAG,
        iter: Mutex::new(iter),
        out_types: bind.out_types.clone(),
        done: false,
    }));
    duckdb_init_set_init_data(info, init as *mut c_void, Some(drop_init_data));
    Ok(())
}

unsafe extern "C" fn func_callback(info: duckdb_function_info, output: duckdb_data_chunk) {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| func_inner(info, output))) {
        Ok(Ok(())) => {}
        Ok(Err(msg)) => func_set_err(info, &msg),
        Err(_) => func_set_err(info, "panic in table-function scan"),
    }
}

unsafe fn func_inner(
    info: duckdb_function_info,
    output: duckdb_data_chunk,
) -> std::result::Result<(), String> {
    // Both the success (TfInitData) and error (TfInitErr) paths
    // install a `#[repr(C)]` box whose first field is a `u8` tag.
    // Read that one byte to discriminate before interpreting the
    // rest of the allocation.
    let raw = duckdb_function_get_init_data(info);
    if raw.is_null() {
        // No init data at all — emit empty chunk = end of scan.
        duckdb_data_chunk_set_size(output, 0);
        return Ok(());
    }
    let tag = *(raw as *const u8);
    if tag == INIT_ERR_TAG {
        let err = &*(raw as *const TfInitErr);
        return Err(err.msg.clone());
    }

    let init = &*(raw as *const TfInitData);
    if init.done {
        duckdb_data_chunk_set_size(output, 0);
        return Ok(());
    }

    let cap = ffi::duckdb_vector_size() as usize;
    let ncols = init.out_types.len();
    let mut produced = 0usize;
    let mut exhausted = false;

    {
        let mut iter = init.iter.lock();
        while produced < cap {
            match iter.next_row() {
                Some(Ok(row)) => {
                    for c in 0..ncols {
                        let vec = ffi::duckdb_data_chunk_get_vector(output, c as idx_t);
                        let val = row.values.get(c).unwrap_or(&FunctionValue::Null);
                        write_cell(vec, produced, val, &init.out_types[c]);
                    }
                    produced += 1;
                }
                Some(Err(e)) => return Err(format!("{e:?}")),
                None => {
                    exhausted = true;
                    break;
                }
            }
        }
    }

    if exhausted {
        // Mark done so the next func call short-circuits. We need
        // interior mutability without a &mut; the bool sits behind
        // a raw write because DuckDB calls func single-threaded
        // for this scan (max_threads = 1).
        let init_mut = raw as *mut TfInitData;
        (*init_mut).done = true;
    }

    duckdb_data_chunk_set_size(output, produced as idx_t);
    Ok(())
}

/// Write `val` into the `row`-th slot of output vector `vec`,
/// using `out_ty` to pick the physical representation.
unsafe fn write_cell(vec: ffi::duckdb_vector, row: usize, val: &FunctionValue, out_ty: &DataType) {
    if matches!(val, FunctionValue::Null) {
        set_vector_null(vec, row);
        return;
    }
    match out_ty {
        DataType::Boolean => write_prim::<bool>(vec, row, val.as_bool().unwrap_or(false)),
        DataType::Int8 => write_prim::<i8>(vec, row, val.as_i64().unwrap_or(0) as i8),
        DataType::Int16 => write_prim::<i16>(vec, row, val.as_i64().unwrap_or(0) as i16),
        DataType::Int32 => write_prim::<i32>(vec, row, val.as_i64().unwrap_or(0) as i32),
        DataType::Int64 => write_prim::<i64>(vec, row, val.as_i64().unwrap_or(0)),
        DataType::UInt8 => write_prim::<u8>(vec, row, val.as_i64().unwrap_or(0) as u8),
        DataType::UInt16 => write_prim::<u16>(vec, row, val.as_i64().unwrap_or(0) as u16),
        DataType::UInt32 => write_prim::<u32>(vec, row, val.as_i64().unwrap_or(0) as u32),
        DataType::UInt64 => write_prim::<u64>(vec, row, val.as_i64().unwrap_or(0) as u64),
        DataType::Float32 => write_prim::<f32>(vec, row, val.as_f64().unwrap_or(0.0) as f32),
        DataType::Float64 => write_prim::<f64>(vec, row, val.as_f64().unwrap_or(0.0)),
        DataType::Char { .. } | DataType::Varchar { .. } | DataType::Text => match val {
            FunctionValue::String(s) => assign_bytes(vec, row, s.as_bytes()),
            FunctionValue::Binary(b) => assign_bytes(vec, row, b),
            other => assign_bytes(vec, row, format!("{other:?}").as_bytes()),
        },
        // BLOB / fallback — write the raw bytes.
        _ => match val {
            FunctionValue::Binary(b) => assign_bytes(vec, row, b),
            FunctionValue::String(s) => assign_bytes(vec, row, s.as_bytes()),
            FunctionValue::Int64(v) => assign_bytes(vec, row, &v.to_le_bytes()),
            FunctionValue::Float64(v) => assign_bytes(vec, row, &v.to_le_bytes()),
            FunctionValue::Boolean(v) => assign_bytes(vec, row, &[*v as u8]),
            _ => set_vector_null(vec, row),
        },
    }
}

unsafe fn write_prim<T: Copy>(vec: ffi::duckdb_vector, row: usize, v: T) {
    let data = ffi::duckdb_vector_get_data(vec) as *mut T;
    std::ptr::write(data.add(row), v);
}

unsafe fn assign_bytes(vec: ffi::duckdb_vector, row: usize, bytes: &[u8]) {
    ffi::duckdb_vector_assign_string_element_len(
        vec,
        row as idx_t,
        bytes.as_ptr() as *const c_char,
        bytes.len() as idx_t,
    );
}

unsafe fn set_vector_null(vec: ffi::duckdb_vector, row: usize) {
    ffi::duckdb_vector_ensure_validity_writable(vec);
    let validity = ffi::duckdb_vector_get_validity(vec);
    if !validity.is_null() {
        ffi::duckdb_validity_set_row_invalid(validity, row as idx_t);
    }
}

/// Read a DuckDB `duckdb_value` parameter into a FunctionValue,
/// using the shim's declared parameter `DataType` to pick the
/// getter.
unsafe fn read_value(val: ffi::duckdb_value, dt: &DataType) -> FunctionValue {
    match dt {
        DataType::Boolean => FunctionValue::Boolean(ffi::duckdb_get_bool(val)),
        DataType::Int8 => FunctionValue::Int8(ffi::duckdb_get_int8(val)),
        DataType::Int16 => FunctionValue::Int16(ffi::duckdb_get_int16(val)),
        DataType::Int32 => FunctionValue::Int32(ffi::duckdb_get_int32(val)),
        DataType::Int64 => FunctionValue::Int64(ffi::duckdb_get_int64(val)),
        DataType::UInt8 => FunctionValue::UInt8(ffi::duckdb_get_uint8(val)),
        DataType::UInt16 => FunctionValue::UInt16(ffi::duckdb_get_uint16(val)),
        DataType::UInt32 => FunctionValue::UInt32(ffi::duckdb_get_uint32(val)),
        DataType::UInt64 => FunctionValue::UInt64(ffi::duckdb_get_uint64(val)),
        DataType::Float32 => FunctionValue::Float32(ffi::duckdb_get_float(val)),
        DataType::Float64 => FunctionValue::Float64(ffi::duckdb_get_double(val)),
        DataType::Char { .. } | DataType::Varchar { .. } | DataType::Text => {
            let p = ffi::duckdb_get_varchar(val);
            if p.is_null() {
                FunctionValue::String(String::new())
            } else {
                let s = std::ffi::CStr::from_ptr(p).to_string_lossy().into_owned();
                ffi::duckdb_free(p as *mut c_void);
                FunctionValue::String(s)
            }
        }
        // BLOB / fallback — pull raw bytes.
        _ => {
            let blob = ffi::duckdb_get_blob(val);
            if blob.data.is_null() || blob.size == 0 {
                FunctionValue::Binary(Vec::new())
            } else {
                let bytes =
                    std::slice::from_raw_parts(blob.data as *const u8, blob.size as usize).to_vec();
                FunctionValue::Binary(bytes)
            }
        }
    }
}

// =====================================================================
// Init-data tagging.
//
// Both the success path (TfInitData) and the error path
// (TfInitErr) install a Box via `duckdb_init_set_init_data`. To
// tell them apart in `func` we put a `u8` tag as the first field
// of each so a single byte read at the box's head discriminates.
// =====================================================================

const INIT_OK_TAG: u8 = 0x0C;
const INIT_ERR_TAG: u8 = 0xE5;

#[repr(C)]
struct TfInitErr {
    tag: u8,
    msg: String,
}

unsafe extern "C" fn drop_extra_info(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    drop(Box::from_raw(ptr as *mut TfExtraInfo));
}

unsafe extern "C" fn drop_bind_data(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    drop(Box::from_raw(ptr as *mut TfBindData));
}

unsafe extern "C" fn drop_init_data(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    drop(Box::from_raw(ptr as *mut TfInitData));
}

unsafe extern "C" fn drop_init_err(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    drop(Box::from_raw(ptr as *mut TfInitErr));
}

unsafe fn bind_set_err(info: duckdb_bind_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_bind_set_error(info, cs.as_ptr() as *const c_char);
    }
}

unsafe fn func_set_err(info: duckdb_function_info, msg: &str) {
    if let Ok(cs) = CString::new(msg) {
        duckdb_function_set_error(info, cs.as_ptr() as *const c_char);
    }
}

// ----------------------------------------------------------------------
// UDTFs the shim publishes.
// ----------------------------------------------------------------------

// === extension: postgis ===
// udtf `st_dump` (arity=1)
// udtf `st_dump_points` (arity=1)
// udtf `st_dump_rings` (arity=1)
// udtf `st_dump_segments` (arity=1)
// udtf `st_dumppoints` (arity=1)
// udtf `st_dumprings` (arity=1)
// udtf `st_dumpsegments` (arity=1)
// udtf `st_hexagon_grid` (arity=2)
// udtf `st_hexagongrid` (arity=2)
// udtf `st_square_grid` (arity=2)
// udtf `st_squaregrid` (arity=2)
// udtf `st_subdivide` (arity=2)
