// === GENERATED by ducklink-shim-codegen — do not edit by hand ===
#![allow(dead_code, unused_imports)]

//! Custom column types — alias BLOB as GEOMETRY, GEOGRAPHY, …
//!
//! Each shim type is registered with DuckDB as an alias for
//! `BLOB`. After registration `CREATE TABLE t (g GEOMETRY)`
//! shows `GEOMETRY` in the schema; storage and the function
//! ABI stay BLOB so existing `ScalarFunctionSignature::exact`
//! signatures keep working unchanged.
//!
//! For each registered type name we call:
//!
//!     handle = duckdb_create_logical_type(DUCKDB_TYPE_BLOB)
//!     duckdb_logical_type_set_alias(handle, "GEOMETRY")
//!     duckdb_register_logical_type(con, handle, NULL)
//!     duckdb_destroy_logical_type(handle)
//!
//! `duckdb_create_type_info` is reserved-for-future-use per
//! upstream comments — we pass NULL. On a name clash with an
//! existing type DuckDB returns DuckDBError; we log+continue
//! to match the policy aggregates_rs uses for scalar/aggregate
//! collisions.

use libduckdb_sys as ffi;
use std::ffi::CString;

/// Register every shim-published custom type as a BLOB alias.
///
/// # Safety
///
/// `con` must be a valid `duckdb_connection` for the duration
/// of this call.
pub unsafe fn register_all(con: ffi::duckdb_connection) {
    if con.is_null() {
        return;
    }
    register_type(con, "postgis:wasm@0.1.0/postgis-aggregates/bbox");
    register_type(con, "postgis:wasm@0.1.0/postgis-aggregates/bbox3d");
    register_type(con, "postgis:wasm@0.1.0/postgis-geocoder/address-component");
    register_type(con, "postgis:wasm@0.1.0/postgis-geocoder/parsed-address");
    register_type(con, "postgis:wasm@0.1.0/postgis-metadata/cast-rewrite");
    register_type(con, "postgis:wasm@0.1.0/postgis-metadata/operator-rewrite");
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-metadata/preprocessor-pattern",
    );
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-accessors/band-metadata",
    );
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-pixels/band-values-entry",
    );
    register_type(con, "postgis:wasm@0.1.0/postgis-raster-pixels/pixel-coord");
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-pixels/pixel-value-coord",
    );
    register_type(con, "postgis:wasm@0.1.0/postgis-raster-stats/histogram-bin");
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-stats/quantile-entry",
    );
    register_type(con, "postgis:wasm@0.1.0/postgis-raster-stats/summary-stats");
    register_type(con, "postgis:wasm@0.1.0/postgis-raster-stats/value-count");
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-stats/value-percent-entry",
    );
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-types/raster-metadata",
    );
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-raster-vector/pixel-vec-entry",
    );
    register_type(
        con,
        "postgis:wasm@0.1.0/postgis-topology-topogeom/topo-element",
    );
    register_type(con, "postgis:wasm@0.1.0/postgis-types/bbox");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/box3d");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/buffer-params");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/coord");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/coord-z");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/coord-zm");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/coordinate-stats");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/extremes");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/inscribed-circle");
    register_type(con, "postgis:wasm@0.1.0/postgis-types/valid-detail");
}

unsafe fn register_type(con: ffi::duckdb_connection, name: &str) {
    let handle = ffi::duckdb_create_logical_type(ffi::DUCKDB_TYPE_DUCKDB_TYPE_BLOB);
    if handle.is_null() {
        eprintln!("[shim-types] could not create logical type for {name}");
        return;
    }
    let c_name = match CString::new(name) {
        Ok(c) => c,
        Err(_) => {
            eprintln!("[shim-types] type name contains NUL: {name}");
            let mut h = handle;
            ffi::duckdb_destroy_logical_type(&mut h);
            return;
        }
    };
    ffi::duckdb_logical_type_set_alias(handle, c_name.as_ptr());
    let rc = ffi::duckdb_register_logical_type(con, handle, std::ptr::null_mut());
    if rc != ffi::DuckDBSuccess {
        // A non-success rc here means a type with this name already
        // exists in the catalog (e.g. DuckDB's built-in GEOMETRY
        // when the spatial extension is loaded, or a re-LOAD of
        // this bridge). Registration is IDEMPOTENT by design: the
        // type stays usable, and since both the pre-existing type
        // and our alias are BLOB-backed at the storage + ABI level,
        // `CREATE TABLE t (g {NAME})` and every BLOB-shaped scalar
        // signature keep working against the existing type. We
        // therefore reuse it rather than treat the clash as an
        // error. Downgraded to an informational note so it doesn't
        // read like a failure.
        eprintln!(
            "[shim-types] type {name} already registered (rc={rc}); reusing the \
             existing BLOB-compatible definition"
        );
    }
    let mut h = handle;
    ffi::duckdb_destroy_logical_type(&mut h);
}

// ----------------------------------------------------------------------
// Column types the shim publishes.
// ----------------------------------------------------------------------

// === extension: postgis ===
// type_id=223325176 name=postgis:wasm@0.1.0/postgis-raster-pixels/pixel-value-coord size=  -1  cast_from=[]  cast_to=[]
// type_id=350294052 name=postgis:wasm@0.1.0/postgis-metadata/preprocessor-pattern size=  -1  cast_from=[]  cast_to=[]
// type_id=393031640 name=postgis:wasm@0.1.0/postgis-raster-stats/summary-stats size=  -1  cast_from=[]  cast_to=[]
// type_id=461550994 name=postgis:wasm@0.1.0/postgis-types/coord-zm size=  -1  cast_from=[]  cast_to=[]
// type_id=837289326 name=postgis:wasm@0.1.0/postgis-aggregates/bbox3d size=  -1  cast_from=[]  cast_to=[]
// type_id=867901609 name=postgis:wasm@0.1.0/postgis-types/inscribed-circle size=  -1  cast_from=[]  cast_to=[]
// type_id=958070342 name=postgis:wasm@0.1.0/postgis-raster-pixels/pixel-coord size=  -1  cast_from=[]  cast_to=[]
// type_id=1051837669 name=postgis:wasm@0.1.0/postgis-geocoder/parsed-address size=  -1  cast_from=[]  cast_to=[]
// type_id=1205495130 name=postgis:wasm@0.1.0/postgis-types/buffer-params size=  -1  cast_from=[]  cast_to=[]
// type_id=1312498754 name=postgis:wasm@0.1.0/postgis-metadata/cast-rewrite size=  -1  cast_from=[]  cast_to=[]
// type_id=1353600900 name=postgis:wasm@0.1.0/postgis-types/coordinate-stats size=  -1  cast_from=[]  cast_to=[]
// type_id=1369622414 name=postgis:wasm@0.1.0/postgis-types/extremes size=  -1  cast_from=[]  cast_to=[]
// type_id=1602695875 name=postgis:wasm@0.1.0/postgis-raster-stats/quantile-entry size=  -1  cast_from=[]  cast_to=[]
// type_id=1649520446 name=postgis:wasm@0.1.0/postgis-raster-types/raster-metadata size=  -1  cast_from=[]  cast_to=[]
// type_id=1658456049 name=postgis:wasm@0.1.0/postgis-raster-vector/pixel-vec-entry size=  -1  cast_from=[]  cast_to=[]
// type_id=1727926893 name=postgis:wasm@0.1.0/postgis-types/coord-z size=  -1  cast_from=[]  cast_to=[]
// type_id=1796423044 name=postgis:wasm@0.1.0/postgis-types/coord size=  -1  cast_from=[]  cast_to=[]
// type_id=1937630734 name=postgis:wasm@0.1.0/postgis-raster-accessors/band-metadata size=  -1  cast_from=[]  cast_to=[]
// type_id=1982891728 name=postgis:wasm@0.1.0/postgis-raster-stats/value-percent-entry size=  -1  cast_from=[]  cast_to=[]
// type_id=2110973180 name=postgis:wasm@0.1.0/postgis-types/box3d size=  -1  cast_from=[]  cast_to=[]
// type_id=2209850317 name=postgis:wasm@0.1.0/postgis-aggregates/bbox size=  -1  cast_from=[]  cast_to=[]
// type_id=2466455033 name=postgis:wasm@0.1.0/postgis-raster-pixels/band-values-entry size=  -1  cast_from=[]  cast_to=[]
// type_id=2478224903 name=postgis:wasm@0.1.0/postgis-raster-stats/value-count size=  -1  cast_from=[]  cast_to=[]
// type_id=2660763088 name=postgis:wasm@0.1.0/postgis-geocoder/address-component size=  -1  cast_from=[]  cast_to=[]
// type_id=2973479800 name=postgis:wasm@0.1.0/postgis-types/valid-detail size=  -1  cast_from=[]  cast_to=[]
// type_id=3010547802 name=postgis:wasm@0.1.0/postgis-types/bbox size=  -1  cast_from=[]  cast_to=[]
// type_id=3180776994 name=postgis:wasm@0.1.0/postgis-metadata/operator-rewrite size=  -1  cast_from=[]  cast_to=[]
// type_id=3745331307 name=postgis:wasm@0.1.0/postgis-topology-topogeom/topo-element size=  -1  cast_from=[]  cast_to=[]
// type_id=3991218132 name=postgis:wasm@0.1.0/postgis-raster-stats/histogram-bin size=  -1  cast_from=[]  cast_to=[]
